spring:
  application:
    name: shopping-service
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USR}
    password: ${DATA_BASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8093
  error:
    include-message: always
management:
  tracing:
    sampling:
      probability: 1.0
